### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by noobLei** [FoRTE-Research/UnTracer-AFL#10]
when i use untracer-afl to fuzz readelf or sfconvert  ,i get the same error " segmentation fault". i can't  solve it ,help me pls, thanks 
![UAN81E7RRU~XA@8X`F91}RL](https://user-images.githubusercontent.com/71857725/124847190-f0ba5d80-dfcc-11eb-9d61-0af8f33c5bd3.png)

**Comment by stevenagy** [comment]
Per the `UnTracerDyninst: No such file or directory`, it seems that you missed adding `UnTracerDyninst` to your `$PATH` environment variable. 

If you still see a segfault after fixing that, see here: https://github.com/FoRTE-Research/UnTracer-AFL/issues/9.

**Comment by noobLei** [comment]
thanks for your help , I solved it . Happy Fuzzing!

**Comment by stevenagy** [comment]
Happy fuzzing!
