### ISSUE TITLE
Get wrong environment  varible in untracer-gcc.c:58

### ISSUE THREAD

**Issue by ChijinZ** [FoRTE-Research/UnTracer-AFL#3]
Is there a mistake in untracer-gcc.c:58? I don't think it is a valid environment varible with "-".
```c++
  u8 *afl_path = getenv("UNTRACER-AFL_PATH");
```

**Comment by stevenagy** [comment]
Good catch! Just fixed it. :)

**Comment by stevenagy** [comment]
Thanks for the pull request! I'm marking this as closed for now - if you encounter any other issues just let me know. :)

Best,
-Stefan
