### ISSUE TITLE
several problems in the installation

### ISSUE THREAD

**Issue by kimiwanano** [FoRTE-Research/UnTracer-AFL#7]
Hi, I have several problems in the installation.
I would like to ask what is the specific operation of this step?
"Update DYN_ROOT in UnTracer-AFL/Makefile to your Dyninst install directory. "
When I skip this step, the resulting error is shown here.

[*] Checking for the ability to commpile x86 code. . .
[+] Everything seems to be working,"ready to compile.
gcc-03 -furoll-loops -wall -D_FORTIFY_SOURCB=2 -g -Wno-pointer-sign -DAFL_PATH= \"/usr/loca1/lib/af1\"-DDOC_ PATH=\"/usr/local/share/doc/afl\” -DBIN_PATH "/usr/local/bin\" untracer-afl.c -o untracer-afl -I/usr/include -I/home/osboxes/ dynBuildDir/include -L/home/osboxes/ dynBuildDir/lib -lcommon -liberty -ldyninstAPI -lboost_system -1dl
/usr/bin/la: cannot find -lcommon
/usr/bin/ld: cannot find -ldyninstAPI
collect2 :_error : ld returned 1 exit status
Makefile:84: recipe for target 'untracer-afl’failed
make:***[untracer-afl] Error 1

Also, does untracer have to run on Ubuntu 18.04? I'm currently using Ubuntu 16.04.
Thanks.

**Comment by kimiwanano** [comment]
Now that I have solved the problem of compiling and installing Untracer, I want to make sure that this work can be done on Ubuntu16.04. Will it have an impact on the follow-up work? Do I need to change to Ubuntu 18.04?

**Comment by stevenagy** [comment]
Both 16.04 and 18.04 should work. :)

**Comment by kimiwanano** [comment]
Thanks a lot！
