### ISSUE TITLE
untracer fuzz

### ISSUE THREAD

**Issue by kimiwanano** [FoRTE-Research/UnTracer-AFL#8]
Hi，when I tried to test with Untracer, I got the error in the figure. Could you please tell me how I can solve this problem?

![image](https://user-images.githubusercontent.com/76025773/114840120-10e0e300-9e09-11eb-939a-eee3e0301190.png)

**Comment by stevenagy** [comment]
You should append the path to the `.so`'s to `LD_LIBRARY_PATH` / `PATH`.

**Comment by kimiwanano** [comment]
Thanks. But I added the path and returned a new error.
![image](https://user-images.githubusercontent.com/76025773/115172168-429ec600-a0f7-11eb-83d9-af3e4afc272a.png)

**Comment by stevenagy** [comment]
Did you instrument the original binary with our provided compiler wrapper? https://github.com/FoRTE-Research/UnTracer-AFL#usage

**Comment by kimiwanano** [comment]
Yes, I have compiled and successfully fuzz the other programs according to the methods in Usage.The only difference is that instead of having a configure file in cjson, it have a MAKEFILE, so I do like this:
CC=/path/to/afl/untracer-clang CXX=/path/to/afl/untracer-clang++ make clean all

The attached figure is the compilation process, I don't know if this is the cause of the problem. Thank you very much for your patience.

![TMXPOSN4HQ~ZOW$8RRLEIVE](https://user-images.githubusercontent.com/76025773/115331236-20c14400-a1c8-11eb-8ee0-f9916265893c.png)

**Comment by stevenagy** [comment]
I notice that `-fPIC` is being passed as a CFLAG. UnTracer-AFL currently only supports non-PIE code - maybe try passing `-no-pie` as a CFLAG?

**Comment by kimiwanano** [comment]
Do it like this?

![WFVL`BLPD 7OW RO85421ZO](https://user-images.githubusercontent.com/76025773/115333593-8283ad00-a1cc-11eb-81bc-7b4ad09fdbed.png)

The same error occurred when I added CFLAG="-no-pie" to compile.

![USM} ) D0Y{`U5G%Z 9I_MJ](https://user-images.githubusercontent.com/76025773/115333609-89aabb00-a1cc-11eb-9951-419953f0ace8.png)

**Comment by stevenagy** [comment]
When you try to run `./out_of_cjson_24h/cjson.tracer`, what error do you get?

**Comment by kimiwanano** [comment]
As shown in figure

![image](https://user-images.githubusercontent.com/76025773/115335499-ebb8ef80-a1cf-11eb-95d9-96503508605b.png)

**Comment by stevenagy** [comment]
I was able to reproduce and fix the error. This should be fixed in https://github.com/FoRTE-Research/UnTracer-AFL/commit/d695ca0ddfcca91a4eed0ad3a374e39b3e00a9a5. Happy fuzzing! :)

**Comment by kimiwanano** [comment]
Thank you very much! Now it can fuzzing normally！

**Comment by stevenagy** [comment]
Awesome! :)

**Comment by noobLei** [comment]
> Yes, I have compiled and successfully fuzz the other programs according to the methods in Usage.The only difference is that instead of having a configure file in cjson, it have a MAKEFILE, so I do like this:
> CC=/path/to/afl/untracer-clang CXX=/path/to/afl/untracer-clang++ make clean all
> 
> The attached figure is the compilation process, I don't know if this is the cause of the problem. Thank you very much for your patience.
> 
> ![TMXPOSN4HQ~ZOW$8RRLEIVE](https://user-images.githubusercontent.com/76025773/115331236-20c14400-a1c8-11eb-8ee0-f9916265893c.png)

**Comment by noobLei** [comment]
when i use untracer-afl to fuzz readelf or sfconvert ,i get the same error " segmentation fault". i can't solve it ,help me pls, thanks

**Comment by noobLei** [comment]
![Uploading UAN81E7RRU~XA@8X`F91}RL.png…]()
